USE digipet;

DROP TABLE IF EXISTS FOTO_X_REPORTE;
DROP TABLE IF EXISTS	REPORTE;
DROP TABLE IF EXISTS	SOLICITUD_X_HOTEL;
DROP TABLE IF EXISTS	SOLICITUD_X_CUIDADOR;
DROP TABLE IF EXISTS	SOLICITUD;
DROP TABLE IF EXISTS	SERVICIO;
DROP TABLE IF EXISTS	HOTEL;
DROP TABLE IF EXISTS	FOTO_X_MASCOTA;
DROP TABLE IF EXISTS	MASCOTA;
DROP TABLE IF EXISTS	TAMANO;
DROP TABLE IF EXISTS	DENUNCIA;
DROP TABLE IF EXISTS	BADGE_X_CUIDADOR;
DROP TABLE IF EXISTS	BADGE;
DROP TABLE IF EXISTS	DISPONIBILIDAD_X_CUIDADOR;
DROP TABLE IF EXISTS	PROVINCIA_X_CUIDADOR;
DROP TABLE IF EXISTS	CUIDADOR;	
DROP TABLE IF EXISTS	UNIVERSIDAD;
DROP TABLE IF EXISTS	PAGO_X_CLIENTE;
DROP TABLE IF EXISTS	CLIENTE;
DROP TABLE IF EXISTS	PROVINCIA;
DROP TABLE IF EXISTS	USUARIO;
DROP TABLE IF EXISTS ESTADO;
DROP TABLE IF EXISTS	ROL;

CREATE TABLE ROL
	(Id_rol					INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(20)		NOT NULL,
	
	PRIMARY KEY(Id_rol));
	
CREATE TABLE ESTADO
	(Id_estado				INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(20)		NOT NULL,
	
	PRIMARY KEY(Id_estado));
	
CREATE TABLE USUARIO
	(Id_usuario				INT				NOT NULL		AUTO_INCREMENT,
	Primer_nombre			VARCHAR(30)		NOT NULL,
	Primer_apellido		VARCHAR(30)		NOT NULL,
	Segundo_apellido		VARCHAR(30),
	Id_rol					INT				NOT NULL,
	Email_1					VARCHAR(30)		NOT NULL,
	Contrasena				VARCHAR(8)		NOT NULL,
	Foto_perfil				VARCHAR(30)		NOT NULL,
	Id_estado					INT				NOT NULL,
	
	PRIMARY KEY(Id_usuario),
	UNIQUE(Email_1));
	
CREATE TABLE PROVINCIA
	(Id_provincia			INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(30)		NOT NULL,
	
	PRIMARY KEY(Id_provincia));
	
CREATE TABLE CLIENTE
	(Id_cliente				INT				NOT NULL,
	Telefono_movil			VARCHAR(10)		NOT NULL,
	Id_provincia			INT				NOT NULL,
	Canton					VARCHAR(30)		NOT NULL,
	Email_2					VARCHAR(30),
	Descripcion				VARCHAR(300)   NOT NULL,
	Fecha_Inscripcion		DATE				NOT NULL,
	
	PRIMARY KEY(Id_cliente));
	

CREATE TABLE PAGO_X_CLIENTE
	(Id_cliente				INT				NOT NULL,
	Metodo_pago				VARCHAR(30)		NOT NULL,
	
	PRIMARY KEY(Id_cliente,Metodo_pago));

CREATE TABLE UNIVERSIDAD
	(Id_universidad		INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(50)		NOT NULL,
	
	PRIMARY KEY(Id_universidad));

CREATE TABLE CUIDADOR
	(Id_cuidador			INT				NOT NULL,
	Carne						VARCHAR(10)		NOT NULL,
	Telefono_movil			VARCHAR(10)		NOT NULL,
	Id_universidad			INT				NOT NULL,
	Canton					VARCHAR(30)		NOT NULL,
	Opcion_provincias		BOOLEAN			NOT NULL,
	Email_2					VARCHAR(30),
	Descripcion				VARCHAR(300)   NOT NULL,
	Fecha_Inscripcion		DATE				NOT NULL,
	
	PRIMARY KEY(Id_cuidador));


CREATE TABLE PROVINCIA_X_CUIDADOR
	(Id_cuidador			INT 				NOT NULL,
	Id_provincia			INT				NOT NULL,
	
	PRIMARY KEY(Id_cuidador,Id_provincia));

CREATE TABLE DISPONIBILIDAD_X_CUIDADOR
	(Id_disponibilidad	INT				NOT NULL		AUTO_INCREMENT,
	Id_cuidador				INT				NOT NULL,
	Fecha_hora_inicio		DATETIME			NOT NULL,
	Fecha_hora_final		DATETIME			NOT NULL,
	
	PRIMARY KEY(Id_disponibilidad));

CREATE TABLE BADGE
	(Id_badge				INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(30)		NOT NULL,
	
	PRIMARY KEY(Id_badge));

CREATE TABLE BADGE_X_CUIDADOR
	(Id_cuidador 			INT				NOT NULL,
	Id_badge					INT				NOT NULL,
	
	PRIMARY KEY(Id_cuidador,Id_badge));			

CREATE TABLE DENUNCIA
	(Id_denuncia			INT				NOT NULL		AUTO_INCREMENT,
	Id_cliente				INT				NOT NULL,
	Id_cuidador				INT				NOT NULL,
	Denuncia					VARCHAR(300)	NOT NULL,
	
	PRIMARY KEY(Id_denuncia));

CREATE TABLE TAMANO
	(Id_tamano				INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(30)		NOT NULL,
	
	PRIMARY KEY(Id_tamano));

CREATE TABLE MASCOTA
	(Id_mascota				INT				NOT NULL		AUTO_INCREMENT,
	Id_cliente				INT				NOT NULL,
	Nombre					VARCHAR(30)		NOT NULL,
	Raza						VARCHAR(30)		NOT NULL,
	Edad						INT				NOT NULL,
	Id_tamano				INT				NOT NULL,
	Descripcion				VARCHAR(300)	NOT NULL,
	Fecha_Inscripcion		DATE				NOT NULL,
	
	PRIMARY KEY(Id_mascota));

CREATE TABLE FOTO_X_MASCOTA
	(Id_mascota				INT				NOT NULL,
	Foto						VARCHAR(30)		NOT NULL,
	
	PRIMARY KEY(Id_mascota,Foto));

CREATE TABLE HOTEL
	(Id_hotel				INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(30)		NOT NULL,
	Direccion				VARCHAR(300)	NOT NULL,
	Capacidad				INT				NOT NULL,
	Descripcion				VARCHAR(300)	NOT NULL,
	
	PRIMARY KEY(Id_hotel));

CREATE TABLE SERVICIO
	(Id_servicio			INT				NOT NULL		AUTO_INCREMENT,
	Nombre					VARCHAR(20)		NOT NULL,
	Precio					INT				NOT NULL,
	
	PRIMARY KEY(Id_servicio));

CREATE TABLE SOLICITUD
	(Id_solicitud			INT				NOT NULL		AUTO_INCREMENT,
	Hora_inicio				DATETIME 		NOT NULL,
	Hora_final				DATETIME			NOT NULL,
	Duracion					INT				NOT NULL,
	Estado					VARCHAR(10)		NOT NULL,
	Precio_unitario		DECIMAL(5,1)	NOT NULL,
	Id_cliente				INT				NOT NULL,
	Id_mascota				INT				NOT NULL,
	Id_servicio				INT				NOT NULL,
	
	CONSTRAINT Chk_duracion CHECK(Duracion <= 8),
	
	PRIMARY KEY(Id_solicitud));

CREATE TABLE SOLICITUD_X_CUIDADOR
	(Id_solicitud			INT				NOT NULL,
	Id_cuidador				INT				NOT NULL,
	Calificacion			DECIMAL(1,1)	NOT NULL,
	Metodo_pago				VARCHAR(30)		NOT NULL,
	Direccion				VARCHAR(300)	NOT NULL,
	Descripcion				VARCHAR(300)	NOT NULL,
	
	PRIMARY KEY(Id_solicitud,Id_cuidador));

CREATE TABLE SOLICITUD_X_HOTEL
	(Id_solicitud			INT				NOT NULL,
	Id_hotel					INT				NOT NULL,
	
	PRIMARY KEY(Id_solicitud,Id_hotel));


CREATE TABLE REPORTE
	(Id_reporte				INT				NOT NULL,
	Cantidad_caca			INT				NOT NULL,
	Cantidad_orines		INT				NOT NULL,
	Cantidad_juegos		INT				NOT NULL,
	Distancia				DECIMAL(2,1)	NOT NULL,
	Detalles					VARCHAR(300)	NOT NULL,
	Id_solicitud			INT				NOT NULL,
	
	PRIMARY KEY(Id_reporte));

CREATE TABLE FOTO_X_REPORTE
	(Id_reporte				INT				NOT NULL,
	Foto						INT				NOT NULL,
	
	PRIMARY KEY(Id_reporte,Foto));
	
	
	
ALTER TABLE USUARIO ADD FOREIGN KEY (Id_rol)	REFERENCES ROL(Id_rol);
ALTER TABLE USUARIO ADD FOREIGN KEY (Id_estado) REFERENCES ESTADO(Id_estado);
ALTER TABLE CLIENTE ADD FOREIGN KEY (Id_provincia)	REFERENCES PROVINCIA(Id_provincia);
ALTER TABLE PAGO_X_CLIENTE ADD FOREIGN KEY (Id_cliente)	REFERENCES CLIENTE(Id_cliente);
ALTER TABLE CUIDADOR ADD FOREIGN KEY (Id_universidad) REFERENCES UNIVERSIDAD(Id_universidad);
ALTER TABLE PROVINCIA_X_CUIDADOR ADD FOREIGN KEY (Id_cuidador) REFERENCES CUIDADOR(Id_cuidador);
ALTER TABLE PROVINCIA_X_CUIDADOR ADD FOREIGN KEY (Id_provincia) REFERENCES PROVINCIA(Id_provincia);
ALTER TABLE DISPONIBILIDAD_X_CUIDADOR ADD FOREIGN KEY (Id_cuidador) REFERENCES CUIDADOR(Id_cuidador);
ALTER TABLE BADGE_X_CUIDADOR ADD FOREIGN KEY (Id_cuidador) REFERENCES CUIDADOR(Id_cuidador);
ALTER TABLE BADGE_X_CUIDADOR ADD FOREIGN KEY (Id_badge) REFERENCES BADGE(Id_badge);
ALTER TABLE DENUNCIA ADD FOREIGN KEY (Id_cliente) REFERENCES CLIENTE(Id_cliente);
ALTER TABLE DENUNCIA ADD FOREIGN KEY (Id_cuidador) REFERENCES CUIDADOR(Id_cuidador);
ALTER TABLE MASCOTA ADD FOREIGN KEY (Id_cliente) REFERENCES CLIENTE(Id_cliente);
ALTER TABLE MASCOTA ADD FOREIGN KEY (Id_tamano) REFERENCES TAMANO(Id_tamano);
ALTER TABLE FOTO_X_MASCOTA ADD FOREIGN KEY (Id_mascota) REFERENCES MASCOTA(Id_mascota);
ALTER TABLE SOLICITUD ADD FOREIGN KEY (Id_cliente) REFERENCES CLIENTE(Id_cliente);
ALTER TABLE SOLICITUD ADD FOREIGN KEY (Id_mascota) REFERENCES MASCOTA(Id_mascota);
ALTER TABLE SOLICITUD ADD FOREIGN KEY (Id_servicio) REFERENCES SERVICIO(Id_servicio);
ALTER TABLE SOLICITUD_X_CUIDADOR ADD FOREIGN KEY (Id_solicitud) REFERENCES SOLICITUD(Id_solicitud);
ALTER TABLE SOLICITUD_X_CUIDADOR ADD FOREIGN KEY (Id_cuidador) REFERENCES CUIDADOR(Id_cuidador);
ALTER TABLE SOLICITUD_X_HOTEL ADD FOREIGN KEY (Id_solicitud) REFERENCES SOLICITUD(Id_solicitud);
ALTER TABLE SOLICITUD_X_HOTEL ADD FOREIGN KEY (Id_hotel) REFERENCES HOTEL(Id_hotel);
ALTER TABLE REPORTE ADD FOREIGN KEY (Id_solicitud) REFERENCES SOLICITUD(Id_solicitud);
ALTER TABLE FOTO_X_REPORTE ADD FOREIGN KEY (Id_reporte) REFERENCES REPORTE(Id_reporte);
	